spring.application.name=oauth2_GITHUB
spring.security.oauth2.client.registration.github.client-id=Ov23libwpPo85kzw3Sfq
spring.security.oauth2.client.registration.github.client-secret=13f0fdfb3b77cdda1e4d176ed0f175bd87966aeb
spring.security.oauth2.client.registration.google.client-id=281814814905-4tk4363tclfpajearnjigh1hhn7bess1.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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